[book]
authors = ["Ian sun"]
multilingual = false
src = "src"
title = "Python3 Man"

[output.html]
additional-css = ["theme/ferris.css", "theme/edition.css"]
additional-js = ["theme/ferris.js"]
mathjax-support = true