#ifndef EXTENDBESTREF_GLOBAL_H
#define EXTENDBESTREF_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EXTENDBESTREF_LIBRARY)
#  define EXTENDBESTREFSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EXTENDBESTREFSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EXTENDBESTREF_GLOBAL_H
