[book]
authors = ["Jane"]
multilingual = false
src = "src"
title = "Rust Programming Language Primer - Rust 编程语言入门"

[output.html]
additional-css = ["ferris.css", "theme/edition.css"]
additional-js = ["ferris.js"]
mathjax-support = true

[output.html.playpen]
editable = true