[book]
authors = ["Ian sun"]
multilingual = false
src = "src"
title = "C++ Get Primer"

[build]
build-dir = "book"
create-missing = true
preprocess = ["links", "index"]

[output.html]
additional-css = ["for-math-theme.css"]
additional-js = ["for-mathjax-config.js"]
mathjax-support = true
