[book]
authors = ["lauer3912"]
multilingual = false
src = "src"
title = "Packages Tools Get Start"

[build]
build-dir = "book"
create-missing = true
preprocess = ["links", "index"]

[output.html]
additional-css = []
additional-js = []
mathjax-support = true
